plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

sourceCompatibility = '17'
targetCompatibility = '17'

javafx {
    version = '17.0.10'
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.swing' ]
}

dependencies {
    // Dependensi tambahan jika diperlukan
    implementation 'org.apache.pdfbox:pdfbox:3.0.1'
}

application {
    mainClass = 'sem3matkul.App'
}

tasks.named('run') {
    standardInput = System.in
}

tasks.register('testPDF', JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'sem3matkul.PDFRendererTest'
}
