plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

sourceCompatibility = '17'
targetCompatibility = '17'

javafx {
    version = '17.0.10'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

dependencies {
    // Dependensi tambahan jika diperlukan
}

application {
    mainClass = 'sem3matkul.App'
}

tasks.named('run') {
    standardInput = System.in
}
